name: data_science_in_life_sciences_project_2026_group_1
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scanpy
  - anndata
  - muon
  - leidenalg
  - python-igraph
  - umap-learn
  - matplotlib
  - seaborn
  - statsmodels
  - pingouin
  - h5py
  - pyarrow
  - scikit-misc
  - tqdm
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - torch
      - mudata
      - captum
      - harmonypy==0.0.9
